version: '3.1'
services:
  rabbitamazonforwarder:
    image: airhelp/rabbit-amazon-forwarder
    ports:
      - "8080:8080"
    volumes:
      - "${MAPPING_FILE}:/config/mapping.json"
      - "${CERTS_DIR:-./certs}:/certs"
    environment:
      MAPPING_FILE: /config/mapping.json
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: "AKIAWISJGQ6J3QMQA7HC"
      AWS_SECRET_ACCESS_KEY: "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"
      CA_CERT_FILE: ${CA_CERT_FILE:- }
      CERT_FILE: ${CERT_FILE:- }
      KEY_FILE: ${KEY_FILE:- }
  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: go test ./...
    depends_on:
      - fmt
      - vet
  vet:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: go vet -v ./...
  fmt:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: gofmt ./...
