version: '2'
services:
  rabbitamazonforwarder:
    image: airhelp/rabbit-amazon-forwarder
    ports:
      - "8080:8080"
    volumes:
      - "${MAPPING_FILE}:/config/mapping.json"
    environment:
      MAPPING_FILE: /config/mapping.json
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      RABBIT_URL_ENV: ${RABBIT_URL_ENV}
