version: '3.1'
services:
  rabbitamazonforwarder:
    image: airhelp/rabbit-amazon-forwarder
    ports:
      - "8080:8080"
    volumes:
      - "${MAPPING_FILE}:/config/mapping.json"
    environment:
      MAPPING_FILE: /config/mapping.json
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: go test ./...
    volumes:
      - ./:/go/src/github.com/AirHelp/rabbit-amazon-forwarder
    depends_on:
      - fmt
      - vet
  vet:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: go vet -v ./...
    volumes:
      - .:/go/src/github.com/AirHelp/rabbit-amazon-forwarder
  fmt:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: gofmt ./...
    volumes:
      - .:/go/src/github.com/AirHelp/rabbit-amazon-forwarder
